import { Inter } from 'next/font/google'
import './globals.css'
import Headers from './components/Headers'
import { ChakraProvider } from '@chakra-ui/react'
import AllRoutes from './AllRoutes'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
   
    <html lang="en">

      <body className={inter.className}>
      <AllRoutes/>
      {children}
      </body>
    </html>
     
    
  )
}
